version: '3.9'

services:

  database:
    image: postgres
    restart: always
    container_name: "database"
    env_file:
      - .env
    ports:
      - "5451:5432"
    networks:
      - custom

networks:
  custom:
    driver: bridge
